name: "Close all issues"
on:
  workflow_dispatch:
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 0
          days-before-close: 0
          stale-issue-message: 'This issue is being closed as part of a bulk closure.'
          close-issue-message: 'Bulk closing all open issues.'
